// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/stpnv0/CommentTree/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCommentService creates a new instance of MockCommentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommentService {
	mock := &MockCommentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommentService is an autogenerated mock type for the CommentService type
type MockCommentService struct {
	mock.Mock
}

type MockCommentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommentService) EXPECT() *MockCommentService_Expecter {
	return &MockCommentService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCommentService
func (_mock *MockCommentService) Create(ctx context.Context, req domain.CreateCommentInput) (domain.Comment, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CreateCommentInput) (domain.Comment, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CreateCommentInput) domain.Comment); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(domain.Comment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.CreateCommentInput) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommentService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCommentService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.CreateCommentInput
func (_e *MockCommentService_Expecter) Create(ctx interface{}, req interface{}) *MockCommentService_Create_Call {
	return &MockCommentService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockCommentService_Create_Call) Run(run func(ctx context.Context, req domain.CreateCommentInput)) *MockCommentService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.CreateCommentInput
		if args[1] != nil {
			arg1 = args[1].(domain.CreateCommentInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommentService_Create_Call) Return(comment domain.Comment, err error) *MockCommentService_Create_Call {
	_c.Call.Return(comment, err)
	return _c
}

func (_c *MockCommentService_Create_Call) RunAndReturn(run func(ctx context.Context, req domain.CreateCommentInput) (domain.Comment, error)) *MockCommentService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCommentService
func (_mock *MockCommentService) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommentService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCommentService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockCommentService_Expecter) Delete(ctx interface{}, id interface{}) *MockCommentService_Delete_Call {
	return &MockCommentService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCommentService_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockCommentService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommentService_Delete_Call) Return(err error) *MockCommentService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommentService_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockCommentService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetTree provides a mock function for the type MockCommentService
func (_mock *MockCommentService) GetTree(ctx context.Context, parentID *int64, params domain.PaginationInput) (domain.CommentTreeResult, error) {
	ret := _mock.Called(ctx, parentID, params)

	if len(ret) == 0 {
		panic("no return value specified for GetTree")
	}

	var r0 domain.CommentTreeResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int64, domain.PaginationInput) (domain.CommentTreeResult, error)); ok {
		return returnFunc(ctx, parentID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int64, domain.PaginationInput) domain.CommentTreeResult); ok {
		r0 = returnFunc(ctx, parentID, params)
	} else {
		r0 = ret.Get(0).(domain.CommentTreeResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *int64, domain.PaginationInput) error); ok {
		r1 = returnFunc(ctx, parentID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommentService_GetTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTree'
type MockCommentService_GetTree_Call struct {
	*mock.Call
}

// GetTree is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID *int64
//   - params domain.PaginationInput
func (_e *MockCommentService_Expecter) GetTree(ctx interface{}, parentID interface{}, params interface{}) *MockCommentService_GetTree_Call {
	return &MockCommentService_GetTree_Call{Call: _e.mock.On("GetTree", ctx, parentID, params)}
}

func (_c *MockCommentService_GetTree_Call) Run(run func(ctx context.Context, parentID *int64, params domain.PaginationInput)) *MockCommentService_GetTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *int64
		if args[1] != nil {
			arg1 = args[1].(*int64)
		}
		var arg2 domain.PaginationInput
		if args[2] != nil {
			arg2 = args[2].(domain.PaginationInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCommentService_GetTree_Call) Return(commentTreeResult domain.CommentTreeResult, err error) *MockCommentService_GetTree_Call {
	_c.Call.Return(commentTreeResult, err)
	return _c
}

func (_c *MockCommentService_GetTree_Call) RunAndReturn(run func(ctx context.Context, parentID *int64, params domain.PaginationInput) (domain.CommentTreeResult, error)) *MockCommentService_GetTree_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockCommentService
func (_mock *MockCommentService) Search(ctx context.Context, query string, params domain.PaginationInput) (domain.SearchResult, error) {
	ret := _mock.Called(ctx, query, params)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 domain.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.PaginationInput) (domain.SearchResult, error)); ok {
		return returnFunc(ctx, query, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.PaginationInput) domain.SearchResult); ok {
		r0 = returnFunc(ctx, query, params)
	} else {
		r0 = ret.Get(0).(domain.SearchResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, domain.PaginationInput) error); ok {
		r1 = returnFunc(ctx, query, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommentService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockCommentService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - params domain.PaginationInput
func (_e *MockCommentService_Expecter) Search(ctx interface{}, query interface{}, params interface{}) *MockCommentService_Search_Call {
	return &MockCommentService_Search_Call{Call: _e.mock.On("Search", ctx, query, params)}
}

func (_c *MockCommentService_Search_Call) Run(run func(ctx context.Context, query string, params domain.PaginationInput)) *MockCommentService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.PaginationInput
		if args[2] != nil {
			arg2 = args[2].(domain.PaginationInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCommentService_Search_Call) Return(searchResult domain.SearchResult, err error) *MockCommentService_Search_Call {
	_c.Call.Return(searchResult, err)
	return _c
}

func (_c *MockCommentService_Search_Call) RunAndReturn(run func(ctx context.Context, query string, params domain.PaginationInput) (domain.SearchResult, error)) *MockCommentService_Search_Call {
	_c.Call.Return(run)
	return _c
}
