// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/stpnv0/CommentTree/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCommentRepository creates a new instance of MockCommentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommentRepository {
	mock := &MockCommentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommentRepository is an autogenerated mock type for the CommentRepository type
type MockCommentRepository struct {
	mock.Mock
}

type MockCommentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommentRepository) EXPECT() *MockCommentRepository_Expecter {
	return &MockCommentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCommentRepository
func (_mock *MockCommentRepository) Create(ctx context.Context, parentID *int64, author string, body string) (*domain.Comment, error) {
	ret := _mock.Called(ctx, parentID, author, body)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int64, string, string) (*domain.Comment, error)); ok {
		return returnFunc(ctx, parentID, author, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int64, string, string) *domain.Comment); ok {
		r0 = returnFunc(ctx, parentID, author, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *int64, string, string) error); ok {
		r1 = returnFunc(ctx, parentID, author, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCommentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID *int64
//   - author string
//   - body string
func (_e *MockCommentRepository_Expecter) Create(ctx interface{}, parentID interface{}, author interface{}, body interface{}) *MockCommentRepository_Create_Call {
	return &MockCommentRepository_Create_Call{Call: _e.mock.On("Create", ctx, parentID, author, body)}
}

func (_c *MockCommentRepository_Create_Call) Run(run func(ctx context.Context, parentID *int64, author string, body string)) *MockCommentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *int64
		if args[1] != nil {
			arg1 = args[1].(*int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCommentRepository_Create_Call) Return(comment *domain.Comment, err error) *MockCommentRepository_Create_Call {
	_c.Call.Return(comment, err)
	return _c
}

func (_c *MockCommentRepository_Create_Call) RunAndReturn(run func(ctx context.Context, parentID *int64, author string, body string) (*domain.Comment, error)) *MockCommentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCommentRepository
func (_mock *MockCommentRepository) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCommentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockCommentRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockCommentRepository_Delete_Call {
	return &MockCommentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCommentRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockCommentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommentRepository_Delete_Call) Return(err error) *MockCommentRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommentRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockCommentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockCommentRepository
func (_mock *MockCommentRepository) GetByID(ctx context.Context, id int64) (*domain.Comment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.Comment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.Comment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCommentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockCommentRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockCommentRepository_GetByID_Call {
	return &MockCommentRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockCommentRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockCommentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommentRepository_GetByID_Call) Return(comment *domain.Comment, err error) *MockCommentRepository_GetByID_Call {
	_c.Call.Return(comment, err)
	return _c
}

func (_c *MockCommentRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.Comment, error)) *MockCommentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTree provides a mock function for the type MockCommentRepository
func (_mock *MockCommentRepository) GetTree(ctx context.Context, parentID *int64, limit int, offset int, sortBy string, sortOrder string) ([]domain.Comment, int, error) {
	ret := _mock.Called(ctx, parentID, limit, offset, sortBy, sortOrder)

	if len(ret) == 0 {
		panic("no return value specified for GetTree")
	}

	var r0 []domain.Comment
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int64, int, int, string, string) ([]domain.Comment, int, error)); ok {
		return returnFunc(ctx, parentID, limit, offset, sortBy, sortOrder)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int64, int, int, string, string) []domain.Comment); ok {
		r0 = returnFunc(ctx, parentID, limit, offset, sortBy, sortOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *int64, int, int, string, string) int); ok {
		r1 = returnFunc(ctx, parentID, limit, offset, sortBy, sortOrder)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *int64, int, int, string, string) error); ok {
		r2 = returnFunc(ctx, parentID, limit, offset, sortBy, sortOrder)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCommentRepository_GetTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTree'
type MockCommentRepository_GetTree_Call struct {
	*mock.Call
}

// GetTree is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID *int64
//   - limit int
//   - offset int
//   - sortBy string
//   - sortOrder string
func (_e *MockCommentRepository_Expecter) GetTree(ctx interface{}, parentID interface{}, limit interface{}, offset interface{}, sortBy interface{}, sortOrder interface{}) *MockCommentRepository_GetTree_Call {
	return &MockCommentRepository_GetTree_Call{Call: _e.mock.On("GetTree", ctx, parentID, limit, offset, sortBy, sortOrder)}
}

func (_c *MockCommentRepository_GetTree_Call) Run(run func(ctx context.Context, parentID *int64, limit int, offset int, sortBy string, sortOrder string)) *MockCommentRepository_GetTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *int64
		if args[1] != nil {
			arg1 = args[1].(*int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockCommentRepository_GetTree_Call) Return(comments []domain.Comment, n int, err error) *MockCommentRepository_GetTree_Call {
	_c.Call.Return(comments, n, err)
	return _c
}

func (_c *MockCommentRepository_GetTree_Call) RunAndReturn(run func(ctx context.Context, parentID *int64, limit int, offset int, sortBy string, sortOrder string) ([]domain.Comment, int, error)) *MockCommentRepository_GetTree_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockCommentRepository
func (_mock *MockCommentRepository) Search(ctx context.Context, query string, limit int, offset int) ([]domain.Comment, int, error) {
	ret := _mock.Called(ctx, query, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []domain.Comment
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]domain.Comment, int, error)); ok {
		return returnFunc(ctx, query, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []domain.Comment); ok {
		r0 = returnFunc(ctx, query, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = returnFunc(ctx, query, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = returnFunc(ctx, query, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCommentRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockCommentRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - limit int
//   - offset int
func (_e *MockCommentRepository_Expecter) Search(ctx interface{}, query interface{}, limit interface{}, offset interface{}) *MockCommentRepository_Search_Call {
	return &MockCommentRepository_Search_Call{Call: _e.mock.On("Search", ctx, query, limit, offset)}
}

func (_c *MockCommentRepository_Search_Call) Run(run func(ctx context.Context, query string, limit int, offset int)) *MockCommentRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCommentRepository_Search_Call) Return(comments []domain.Comment, n int, err error) *MockCommentRepository_Search_Call {
	_c.Call.Return(comments, n, err)
	return _c
}

func (_c *MockCommentRepository_Search_Call) RunAndReturn(run func(ctx context.Context, query string, limit int, offset int) ([]domain.Comment, int, error)) *MockCommentRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}
